### ISSUE TITLE
NullPointerException thrown when executing the wikipedia workload

### ISSUE THREAD

**Issue by sensssz** [oltpbenchmark/oltpbench#102]
First, in file config/sample_wiki_config.xml, the database name is ycsb.

Second, when executing the wikipedia using this config file with correct server address, username and password, a NullPointerException is thrown:
```
Exception in thread "main" java.lang.RuntimeException: Failed to create new instance of WikipediaBenchmark
        at com.oltpbenchmark.util.ClassUtil.newInstance(ClassUtil.java:182)
        at com.oltpbenchmark.util.ClassUtil.newInstance(ClassUtil.java:166)
        at com.oltpbenchmark.DBWorkload.main(DBWorkload.java:231)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at com.oltpbenchmark.util.ClassUtil.newInstance(ClassUtil.java:180)
        ... 2 more
Caused by: java.lang.NullPointerException
        at java.io.File.<init>(File.java:277)
        at com.oltpbenchmark.benchmarks.wikipedia.WikipediaBenchmark.<init>(WikipediaBenchmark.java:65)
        ... 7 more
```

**Comment by apavlo** [comment]
Try these fixes.
