### ISSUE TITLE
Run YCSB workload and received Java runtime exception

### ISSUE THREAD

**Issue by yihchuang** [oltpbenchmark/oltpbench#109]
The following runtime exception was raised.  Any suggestions?  Thank you.

[cloud-user@novavm4qa oltpbench]$ ./oltpbenchmark -b tpcc -c ./config/yih_pgycsb_config.xml  --create=true --load=true --execute=true -s 5 -o  ./output/yih/ycsb/ycsb
10:28:40,029 (DBWorkload.java:242) INFO  - **********************************************************************************

Benchmark:     TPCC {com.oltpbenchmark.benchmarks.tpcc.TPCCBenchmark}
Configuration: ./config/yih_pgycsb_config.xml
Type:          MYSQL
Driver:        com.mysql.jdbc.Driver
URL:           jdbc:mysql://192.168.30.61:3306/tpcDB
Isolation:     TRANSACTION_SERIALIZABLE
Scale Factor:  1000.0

10:28:40,030 (DBWorkload.java:243) INFO  - **********************************************************************************
Exception in thread "main" java.lang.RuntimeException: Failed to retrieve class for com.oltpbenchmark.benchmarks.tpcc.procedures.ReadRecord
        at com.oltpbenchmark.util.ClassUtil.getClass(ClassUtil.java:275)
        at com.oltpbenchmark.api.BenchmarkModule.initTransactionType(BenchmarkModule.java:360)
        at com.oltpbenchmark.DBWorkload.main(DBWorkload.java:269)
Caused by: java.lang.ClassNotFoundException: com.oltpbenchmark.benchmarks.tpcc.procedures.ReadRecord
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at com.oltpbenchmark.util.ClassUtil.getClass(ClassUtil.java:273)
        ... 2 more

When ran the following workload:
[cloud-user@novavm4qa oltpbench]$ cat ./config/yih_pgycsb_config.xml
<?xml version="1.0"?>
<parameters>
    
    <dbtype>mysql</dbtype>
    <driver>com.mysql.jdbc.Driver</driver>
    <DBUrl>jdbc:mysql://192.168.30.61:3306/tpcDB</DBUrl>
    <username>dbuser</username>
    <password>eusjwkd@aA1</password>

    
    <scalefactor>1000</scalefactor>

    
    <terminals>10</terminals>
    <works>
        <work>
          <time>3000</time>
          <rate>unlimited</rate>
          <weights>50,50,0,0,0,0</weights>
        </work>
    </works>

    
    <transactiontypes>
        <transactiontype>
                <name>ReadRecord</name>
        </transactiontype>
        <transactiontype>
                <name>InsertRecord</name>
        </transactiontype>
        <transactiontype>
                <name>ScanRecord</name>
        </transactiontype>
        <transactiontype>
                <name>UpdateRecord</name>
        </transactiontype>
        <transactiontype>
                <name>DeleteRecord</name>
        </transactiontype>
        <transactiontype>
                <name>ReadModifyWriteRecord</name>
        </transactiontype>
    </transactiontypes>
</parameters>

**Comment by apavlo** [comment]
You are trying to run the **TPC-C** benchmark with a **YCSB** configuration file. This is not a bug.

**Comment by yihchuang** [comment]
Thank you Andy.

Regards,

--Yih
