### ISSUE TITLE
SEATS throws RunTimeException loading 615 scale factor for postgres

### ISSUE THREAD

**Issue by mw2q** [oltpbenchmark/oltpbench#111]
Ran into this against commit 27771705c01b3b0f8b56ba0a8579d578d438f99e and PostgreSQL 9.6devel when executing:

> ./oltpbenchmark -b seats -c pgsql_seats_config.xml -d /tmp/seats --create=true --load=true --execute=false -s 5 -o seats-load

This is the exception:

> Exception in thread "main" java.lang.RuntimeException: Failed to load data files for scaling-sized table 'FLIGHT'                                                                            
>         at com.oltpbenchmark.benchmarks.seats.SEATSLoader.loadScalingTables(SEATSLoader.java:233)                                                                                            
>         at com.oltpbenchmark.benchmarks.seats.SEATSLoader.load(SEATSLoader.java:128)                                                                                                         
>         at com.oltpbenchmark.api.BenchmarkModule.loadDatabase(BenchmarkModule.java:284)                                                                                                      
>         at com.oltpbenchmark.api.BenchmarkModule.loadDatabase(BenchmarkModule.java:268)                                                                                                      
>         at com.oltpbenchmark.DBWorkload.runLoader(DBWorkload.java:690)                                                                                                                       
>         at com.oltpbenchmark.DBWorkload.main(DBWorkload.java:522)                                                                                                                            
> Caused by: java.lang.RuntimeException: Failed to load table FLIGHT                                                                                                                           
>         at com.oltpbenchmark.benchmarks.seats.SEATSLoader.loadTable(SEATSLoader.java:381)                                                                                                    
>         at com.oltpbenchmark.benchmarks.seats.SEATSLoader.loadScalingTables(SEATSLoader.java:231)                                                                                            
>         ... 5 more                                                                                                                                                                           
> Caused by: java.sql.BatchUpdateException: Batch entry 3,578 INSERT INTO "FLIGHT" VALUES ('6263054459143207', '1063', '252', '2044-03-05 13:17:09.982000 +01:00:00', '220', '2044-04-16 06:17:09.982000 +02:00:00', '0', '399.0', '150', '147', '119473961', '522234765', '245083163', '1037492404', '965290148', '194851978', '498910712', '918737513', '25793002', '351066013', '916316086', '838095445', '222076132', '172059223', '647491246', '499935012', '163659104', '243064984', '677258309', '658175328', '777683295', '1007205247', '385051778', '564646543', '192302227', '360680948', '556245924', '586060419', '450169993', '805591215') was aborted.  Call getNextException to see the cause.
>         at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2621)                                                                      
>         at org.postgresql.core.v3.QueryExecutorImpl$1.handleError(QueryExecutorImpl.java:459)                                                                                                
>         at org.postgresql.core.v3.QueryExecutorImpl$ErrorTrackingResultHandler.handleError(QueryExecutorImpl.java:348)                                                                       
>         at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1837)                                                                                              
>         at org.postgresql.core.v3.QueryExecutorImpl.sendQuery(QueryExecutorImpl.java:1091)                                                                                                   
>         at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:398)                                                                                                      
>         at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2754)                                                                                        
>         at com.oltpbenchmark.benchmarks.seats.SEATSLoader.loadTable(SEATSLoader.java:367)                                                                                                    
>         ... 6 more

This is the config used:

> <?xml version="1.0"?>
> <parameters>
>
>     
>     <dbtype>postgres</dbtype>
>     <driver>org.postgresql.Driver</driver>
>     <DBUrl>jdbc:postgresql://localhost:5432/seats</DBUrl>
>     <username>user</username>
>     <password>password</password>
>     <isolation>TRANSACTION_SERIALIZABLE</isolation>
>
>     
>     <scalefactor>615</scalefactor>
>
>     
>     <terminals>10</terminals>
>     <works>
>         <work>
>           <time>300</time>
>           <rate>10000</rate>
>           <weights>10, 10, 35, 20, 10, 15</weights>
>         </work>
>     </works>
>
>     
>     <transactiontypes>
>         <transactiontype>
>                 <name>DeleteReservation</name>
>         </transactiontype>
>         <transactiontype>
>                 <name>FindFlights</name>
>         </transactiontype>
>         <transactiontype>
>                 <name>FindOpenSeats</name>
>         </transactiontype>
>         <transactiontype>
>                 <name>NewReservation</name>
>         </transactiontype>
>         <transactiontype>
>                 <name>UpdateCustomer</name>
>         </transactiontype>
>         <transactiontype>
>                 <name>UpdateReservation</name>
>         </transactiontype>
>     </transactiontypes>
> </parameters>

**Comment by apavlo** [comment]
Can you try it with a lower scale factor? I think there is an overflow
problem.

**Comment by mw2q** [comment]
On 12/21/15 11:27, Andy Pavlo wrote:
> Can you try it with a lower scale factor? I think there is an overflow
> problem.

Yeah, it runs fine using a scale factor of 1.

**Comment by apavlo** [comment]
Not sure what you're trying to do, but you can try it with 100, 200, 300, 400, 500, 600 until it fails

On Monday, December 21, 2015 11:57 AM Mark Wong wrote:
> On 12/21/15 11:27, Andy Pavlo wrote:
> > Can you try it with a lower scale factor? I think there is an overflow
> > problem.
> 
> Yeah, it runs fine using a scale factor of 1.
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/oltpbenchmark/oltpbench/issues/111#issuecomment-166403117

-- 
Andy Pavlo
pavlo@cs.cmu.edu

**Comment by mw2q** [comment]
On 12/21/15 13:12, Andy Pavlo wrote:
> Not sure what you're trying to do, but you can try it with 100, 200, 300, 400, 500, 600 until it fails

I'm trying to run tests with at least 100GB data sets.  615 was what I
estimated from the scale factor of 1.

Does finding the breaking point help fix things for the larger scale
factors, or is this particular test not interesting at larger scale factors?
