### ISSUE TITLE
how i can run the oltpbenchmark 

### ISSUE THREAD

**Issue by nona89** [oltpbenchmark/oltpbench#120]

**Comment by apavlo** [comment]
What is the error message that you are experiencing?

**Comment by nona89** [comment]
i can not update the configration file for oltpbenchmark to be run on ubuntu

**Comment by apavlo** [comment]
What is the error message?

**Comment by nona89** [comment]
it give me this error message 
Exception in thread "main" java.lang.RuntimeException: Failed to retrieve class for com.oltpbenchmark.benchmarks.tpcc.procedures.AddWatchList
        at com.oltpbenchmark.util.ClassUtil.getClass(ClassUtil.java:275)
        at com.oltpbenchmark.api.BenchmarkModule.initTransactionType(BenchmarkModule.java:360)
        at com.oltpbenchmark.DBWorkload.main(DBWorkload.java:269)
Caused by: java.lang.ClassNotFoundException: com.oltpbenchmark.benchmarks.tpcc.procedures.AddWatchList
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at com.oltpbenchmark.util.ClassUtil.getClass(ClassUtil.java:273)

**Comment by apavlo** [comment]
Why are you commenting on another issue #100? Do you not know how the website works?

You have still not told me what problem you are facing. I can't tell you how to edit a text file.

**Comment by apavlo** [comment]
`AddWatchList` is not a TPC-C stored procedure. You are using the Wikipedia config file with TPC-C. This is not a bug.
