### ISSUE TITLE
AUCTIONMARK and SEATS- UNQIUE INDEX - PRIMARY KEY Rollback

### ISSUE THREAD

**Issue by skapila** [oltpbenchmark/oltpbench#130]
While executing these two workload on single client .The New ITEM transcaction in the auctionmark is rolling back due to repetition of same ITEM_ID 

How to avoid these rollbacks?

**Comment by apavlo** [comment]
How long did you run the benchmark for? What scalefactor?

**Comment by skapila** [comment]
I executed it  for 30 seconds with  1 scalefactor and 1 terminal

**Comment by apavlo** [comment]
Try it with a larger scale factor. You might be burning through the IDs too quickly.

On Saturday, November 5, 2016 12:09:38 PM EST skapila wrote:
> I executed it  for 30 seconds with  1 scalefactor and 1 terminal  
> 
> 


-- 
Andy Pavlo
pavlo@cs.cmu.edu

**Comment by skapila** [comment]
I tried to execute the Auctionmark workload  for 5 min with 10 scale factor.But these rollbacks are still  there.
==================================================================
# ERROR:-
10:26:15,923 (AuctionMarkWorker.java:279) DEBUG - Checking whether we can execute NewItem now
10:26:15,923 (NewItem.java:164) DEBUG - NewItem :: run
10:26:15,923 (NewItem.java:165) DEBUG - >> ## item_id = 5497558402151 , ## seller_id = 263271, category_id = 916
10:26:15,924 (NewItem.java:166) DEBUG - >> name = vnjozpewhyoywfsrehooc , description length = 85
10:26:15,924 (NewItem.java:167) DEBUG - >> initial_price = 34.0 , attributes length = 106
10:26:15,924 (NewItem.java:168) DEBUG - >> gag_ids[].length = 1 , gav_ids[] length = 1
10:26:15,924 (NewItem.java:169) DEBUG - >> image length = 4
10:26:15,924 (NewItem.java:170) DEBUG - >> start = 2016-11-07 10:10:38.6, end = 2016-11-15 10:10:38.6
10:26:15,930 (Worker.java:377) DEBUG - ## NewItem/08 Aborted
com.oltpbenchmark.benchmarks.auctionmark.exceptions.DuplicateItemIdException: ## Duplicate ItemId #5497558402151 for Seller #263271
        at com.oltpbenchmark.benchmarks.auctionmark.procedures.NewItem.run(NewItem.java:247)
        at com.oltpbenchmark.benchmarks.auctionmark.AuctionMarkWorker.executeNewItem(AuctionMarkWorker.java:788)
        at com.oltpbenchmark.benchmarks.auctionmark.AuctionMarkWorker.executeWork(AuctionMarkWorker.java:387)
        at com.oltpbenchmark.api.Worker.doWork(Worker.java:373)
        at com.oltpbenchmark.api.Worker.run(Worker.java:282)
        at java.lang.Thread.run(Unknown Source)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '5497558402151-263271' for key 'PRIMARY'
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
        at com.mysql.jdbc.Util.getInstance(Util.java:386)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1040)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4096)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4028)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2490)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2651)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2734)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2155)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2458)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2375)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2359)
        at com.oltpbenchmark.benchmarks.auctionmark.procedures.NewItem.run(NewItem.java:238)
        ... 5 more



==================================================================
# OUTPUT RESULT:-

10:21:49,993 (ThreadBench.java:232) INFO  - Starting WatchDogThread
10:21:50,232 (DBWorkload.java:706) INFO  - **********************************************************************************
10:21:50,233 (DBWorkload.java:707) INFO  - Rate limited reqs/s: Results(nanoSeconds=300000065190, measuredRequests=148868) = 496.2265588366354 requests/sec
10:21:50,273 (DBWorkload.java:572) INFO  - Output into file: outputfile.8.res
10:21:50,284 (DBWorkload.java:576) INFO  - Output Raw data into file: outputfile.8.raw
Our result uploadercom.oltpbenchmark.util.ResultUploader@1b8cce2
10:21:50,285 (DBWorkload.java:581) INFO  - Output summary data into file: outputfile.8.summary
10:21:50,286 (DBWorkload.java:587) INFO  - Output db config into file: outputfile.8.db
10:21:50,289 (DBWorkload.java:593) INFO  - Output benchmark config into file: outputfile.8.ben
10:21:50,316 (DBWorkload.java:602) INFO  - Grouped into Buckets of 5 seconds
10:21:50,381 (DBWorkload.java:630) INFO  - **********************************************************************************
10:21:50,381 (DBWorkload.java:631) INFO  - Completed Transactions:
GetItem/02           [67058] ********************************************************************************
GetUserInfo/03       [14774] *****************
NewBid/04            [29831] ***********************************
NewComment/05        [ 2860] ***
NewCommentRespons... [ 1533] *
NewFeedback/07       [ 5849] ******
NewItem/08           [14991] *****************
NewPurchase/09       [ 7506] ********
UpdateItem/10        [ 4467] *****
ResetDatabase/171... [    0]
CloseAuctions/185... [    0]
LoadConfig/202966... [    0]

10:21:50,382 (DBWorkload.java:632) INFO  - Aborted Transactions:
GetItem/02           [   0]
GetUserInfo/03       [   0]
NewBid/04            [   0]
NewComment/05        [   0]
NewCommentRespons... [   0]
NewFeedback/07       [   0]
# NewItem/08           [ 825] *******************************************************************
NewPurchase/09       [  48] ****
UpdateItem/10        [   0]
ResetDatabase/171... [   0]
CloseAuctions/185... [   0]
LoadConfig/202966... [   0]
