### ISSUE TITLE
auctionmark - Duplicate entry - executeNewPurchase() - mysql

### ISSUE THREAD

**Issue by grooverdan** [oltpbenchmark/oltpbench#138]
config/sample_auctionmark_config.xml with scalefactor=1

https://travis-ci.org/grooverdan/oltpbench/jobs/213287221
<pre>
05:55:39,871 (Worker.java:481) WARN  - The DBMS rejected the transaction without an error code

com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '445865159203225639-58475-8796093546535-524327' for key 'PRIMARY'
	at sun.reflect.GeneratedConstructorAccessor9.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1040)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4096)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4028)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2490)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2651)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2734)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2155)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2458)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2375)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2359)
	at com.oltpbenchmark.benchmarks.auctionmark.procedures.NewPurchase.run(NewPurchase.java:203)
	at com.oltpbenchmark.benchmarks.auctionmark.AuctionMarkWorker.executeNewPurchase(AuctionMarkWorker.java:827)
	at com.oltpbenchmark.benchmarks.auctionmark.AuctionMarkWorker.executeWork(AuctionMarkWorker.java:390)
	at com.oltpbenchmark.api.Worker.doWork(Worker.java:380)
	at com.oltpbenchmark.api.Worker.run(Worker.java:290)
	at java.lang.Thread.run(Thread.java:745)
</pre>

**Comment by grooverdan** [comment]
For things like NewPurchase, the order number should be autoincrement/serial as this is how real applications do it. They don't rely on pushing a potentially conflicting value which reorders the data in the database.

**Comment by apavlo** [comment]
I think that the issue was that we didn't have autoinc in H-Store when I originally wrote this benchmark

**Comment by grooverdan** [comment]
still not apparently: workaround https://forum.voltdb.com/showthread.php?355-Auto-Increment&p=1233&viewfull=1#post1233
