### ISSUE TITLE
JPAB - fails to create schema - no schema DDL

### ISSUE THREAD

**Issue by grooverdan** [oltpbenchmark/oltpbench#144]
https://travis-ci.org/grooverdan/oltpbench/jobs/214103047
https://travis-ci.org/grooverdan/oltpbench/jobs/214103062
<pre>
04:08:45,759 (DBWorkload.java:259) INFO  - ======================================================================

Benchmark:     JPAB {com.oltpbenchmark.benchmarks.jpab.JPABBenchmark}
Configuration: config/sample_jpab_config.xml
Type:          POSTGRES
Driver:        org.postgresql.Driver
URL:           jdbc:postgresql://localhost:5432/jpab
Isolation:     TRANSACTION_READ_COMMITTED
Scale Factor:  1.0

04:08:45,766 (DBWorkload.java:260) INFO  - ======================================================================
04:08:45,799 (DBWorkload.java:512) INFO  - Creating new JPAB database...
04:08:45,895 (BenchmarkModule.java:192) ERROR - Failed to find DDL file for jpab

Exception in thread "main" java.lang.RuntimeException: Unexpected error when trying to create the jpab database
	at com.oltpbenchmark.api.BenchmarkModule.createDatabase(BenchmarkModule.java:242)
	at com.oltpbenchmark.api.BenchmarkModule.createDatabase(BenchmarkModule.java:222)
	at com.oltpbenchmark.DBWorkload.runCreator(DBWorkload.java:778)
	at com.oltpbenchmark.DBWorkload.main(DBWorkload.java:513)
Caused by: java.lang.NullPointerException
	at com.oltpbenchmark.util.ScriptRunner.runScript(ScriptRunner.java:95)
	at com.oltpbenchmark.api.BenchmarkModule.createDatabase(BenchmarkModule.java:240)
	... 3 more
</pre>

**Comment by davidlday** [comment]
Possible duplicate of #52.
