### ISSUE TITLE
auctionmark: getItemComments wrong number of arguments

### ISSUE THREAD

**Issue by grooverdan** [oltpbenchmark/oltpbench#155]
https://travis-ci.org/grooverdan/oltpbench/jobs/216197933

<pre>
04:00:31,425 (Worker.java:481) WARN  - The DBMS rejected the transaction without an error code
org.postgresql.util.PSQLException: The column index is out of range: 2, number of columns: 1.
	at org.postgresql.core.v3.SimpleParameterList.bind(SimpleParameterList.java:63)
	at org.postgresql.core.v3.SimpleParameterList.setBinaryParameter(SimpleParameterList.java:131)
	at org.postgresql.jdbc.PgPreparedStatement.bindBytes(PgPreparedStatement.java:1094)
	at org.postgresql.jdbc.PgPreparedStatement.setInt(PgPreparedStatement.java:315)
	at org.postgresql.jdbc.PgPreparedStatement.setObject(PgPreparedStatement.java:1010)
	at com.oltpbenchmark.api.Procedure.getPreparedStatement(Procedure.java:107)
	at com.oltpbenchmark.benchmarks.auctionmark.procedures.GetUserInfo.run(GetUserInfo.java:142)
	at com.oltpbenchmark.benchmarks.auctionmark.AuctionMarkWorker.executeGetUserInfo(AuctionMarkWorker.java:525)
	at om.oltpbenchmark.benchmarks.auctionmark.AuctionMarkWorker.executeWork(AuctionMarkWorker.java:372)
	at com.oltpbenchmark.api.Worker.doWork(Worker.java:380)
	at com.oltpbenchmark.api.Worker.run(Worker.java:290)
	at java.lang.Thread.run(Thread.java:745)
</pre>

**Comment by grooverdan** [comment]
Thanks @dvanaken for your fixes.
