### ISSUE TITLE
Caught SQL Exception in WikipediaWorker for Wikipedia Benchmark

### ISSUE THREAD

**Issue by shraddha18** [oltpbenchmark/oltpbench#173]
I get this error on MySQL when I run Wikipedia benchmark:
```
15:34:26,866 (ThreadBench.java:428) INFO  - TERMINATE :: Waiting for all terminals to finish ..
15:35:08,117 (WikipediaWorker.java:112) ERROR - Caught SQL Exception in WikipediaWorker for procedurecom.oltpbenchmark.benchmarks.wikipedia.procedures.GetPageAnonymous:java.sql.SQLException: Lock wait timeout exceeded; try restarting transaction
java.sql.SQLException: Lock wait timeout exceeded; try restarting transaction
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1074)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4096)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4028)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2490)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2651)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2734)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2155)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2322)
	at com.oltpbenchmark.benchmarks.wikipedia.procedures.GetPageAnonymous.run(GetPageAnonymous.java:74)
	at com.oltpbenchmark.benchmarks.wikipedia.WikipediaWorker.getPageAnonymous(WikipediaWorker.java:140)
	at com.oltpbenchmark.benchmarks.wikipedia.WikipediaWorker.executeWork(WikipediaWorker.java:100)
	at com.oltpbenchmark.api.Worker.doWork(Worker.java:380)
	at com.oltpbenchmark.api.Worker.run(Worker.java:290)
	at java.lang.Thread.run(Thread.java:745)
```
Everything seems to work fine but I would like to know if anyone faced this problem too.

**Comment by LiYueguang6** [comment]
I'm facing this problem now, but there is no one came to solve this problem.
