### ISSUE TITLE
Duplicate primary key problems in AuctionMark

### ISSUE THREAD

**Issue by samehdi** [oltpbenchmark/oltpbench#247]
I am getting a lot of duplicate primary key exceptions while running the AuctionMark benchmark on MyRocks. The source seems to be the [getUniqueElementId function](https://github.com/oltpbenchmark/oltpbench/blob/8b749cac799a5406ee8d0e64b14d050fe87a96a1/src/com/oltpbenchmark/benchmarks/auctionmark/util/AuctionMarkUtil.java#L65)

One of the problems seems to have been a possible incorrect left shift. I have initiated a [pull request](https://github.com/oltpbenchmark/oltpbench/pull/245) for that.

The second problem seems to be [this call](https://github.com/oltpbenchmark/oltpbench/blob/8b749cac799a5406ee8d0e64b14d050fe87a96a1/src/com/oltpbenchmark/benchmarks/auctionmark/AuctionMarkWorker.java#L815) to that function. Why is random number generation needed here ? Can this be solved by sequentially allocating 7-bit purchase ids ? Is it possible that 128 numbers are not sufficient for the rate at which new purchase ids are generated ?

`14:52:22,385 (Worker.java:492) WARN  - The DBMS rejected the transaction without an error code
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '27034791904608526-740525-13194140385550-852238' for key 'PRIMARY'
        at sun.reflect.GeneratedConstructorAccessor8.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
        at com.mysql.jdbc.Util.getInstance(Util.java:386)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1040)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4096)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4028)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2490)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2651)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2734)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2155)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2458)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2375)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2359)
        at com.oltpbenchmark.benchmarks.auctionmark.procedures.NewPurchase.run(NewPurchase.java:203)
        at com.oltpbenchmark.benchmarks.auctionmark.AuctionMarkWorker.executeNewPurchase(AuctionMarkWorker.java:827)
        at com.oltpbenchmark.benchmarks.auctionmark.AuctionMarkWorker.executeWork(AuctionMarkWorker.java:390)
        at com.oltpbenchmark.api.Worker.doWork(Worker.java:386)
        at com.oltpbenchmark.api.Worker.run(Worker.java:296)
        at java.lang.Thread.run(Thread.java:748)
`

**Comment by apavlo** [comment]
@samehdi I don't remember what I was doing in that function or why I have the giant "HACK" in there. What happens if you replace the rng with your proposed fix?

**Comment by samehdi** [comment]
Sequentially allocating 7-bit integers per Item-Id fixed the problem (for my current setup at least scalefactor = 10, terminals = 10). I have updated my existing [pull request](https://github.com/oltpbenchmark/oltpbench/pull/245) with the proposed fix.
