### ISSUE TITLE
Wikipedia workload error: Data truncation: Data too long for column 'rc_comment' at row 1

### ISSUE THREAD

**Issue by zhj4655** [oltpbenchmark/oltpbench#265]
The complete:
`09:54:35,606 (DBWorkload.java:262) INFO  - ======================================================================

Benchmark:     WIKIPEDIA {com.oltpbenchmark.benchmarks.wikipedia.WikipediaBenchmark}
Configuration: /vdb/project/oltpbench/config/sample_wikipedia_config.xml
Type:          MYSQL
Driver:        com.mysql.jdbc.Driver
URL:           jdbc:mysql://localhost:3306/wikipedia
Isolation:     TRANSACTION_REPEATABLE_READ
Scale Factor:  10.0

09:54:35,608 (DBWorkload.java:263) INFO  - ======================================================================
09:54:35,625 (DBWorkload.java:820) INFO  - Creating 10 virtual terminals...
09:54:36,009 (DBWorkload.java:825) INFO  - Launching the WIKIPEDIA Benchmark with 1 Phase...
09:54:36,087 (ThreadBench.java:327) INFO  - PHASE START :: [Workload=WIKIPEDIA] [Serial=false] [Time=300] [WarmupTime=30] [Rate=unlimited] [Arrival=REGULAR] [Ratios=[0.07, 0.07, 7.6725, 91.2656, 0.9219]] [ActiveWorkers=10]
09:55:06,088 (ThreadBench.java:478) INFO  - MEASURE :: Warmup complete, starting measurements.
09:57:40,572 (WikipediaWorker.java:111) ERROR - Caught SQL Exception in WikipediaWorker for procedurecom.oltpbenchmark.benchmarks.wikipedia.procedures.UpdatePage:com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'rc_comment' at row 1
com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'rc_comment' at row 1
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4094)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4028)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2490)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2651)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2734)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2155)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1379)
	at com.oltpbenchmark.benchmarks.wikipedia.procedures.UpdatePage.execute(UpdatePage.java:316)
	at com.oltpbenchmark.benchmarks.wikipedia.procedures.UpdatePage.run(UpdatePage.java:219)
	at com.oltpbenchmark.benchmarks.wikipedia.WikipediaWorker.updatePage(WikipediaWorker.java:182)
	at com.oltpbenchmark.benchmarks.wikipedia.WikipediaWorker.executeWork(WikipediaWorker.java:98)
	at com.oltpbenchmark.api.Worker.doWork(Worker.java:386)
	at com.oltpbenchmark.api.Worker.run(Worker.java:296)
	at java.lang.Thread.run(Thread.java:748)
09:57:40,596 (Worker.java:495) WARN  - The DBMS rejected the transaction without an error code
com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'rc_comment' at row 1
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4094)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4028)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2490)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2651)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2734)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2155)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1379)
	at com.oltpbenchmark.benchmarks.wikipedia.procedures.UpdatePage.execute(UpdatePage.java:316)
	at com.oltpbenchmark.benchmarks.wikipedia.procedures.UpdatePage.run(UpdatePage.java:219)
	at com.oltpbenchmark.benchmarks.wikipedia.WikipediaWorker.updatePage(WikipediaWorker.java:182)
	at com.oltpbenchmark.benchmarks.wikipedia.WikipediaWorker.executeWork(WikipediaWorker.java:98)
	at com.oltpbenchmark.api.Worker.doWork(Worker.java:386)
	at com.oltpbenchmark.api.Worker.run(Worker.java:296)
	at java.lang.Thread.run(Thread.java:748)
`
Why cause this error, and what should I do to fix it?

**Comment by lmwnshn** [comment]
@apavlo This is new, previously we were running into uniqueness issues not truncation ones. 

I'm actually surprised this is happening. We generate a random truncated string [here](https://github.com/oltpbenchmark/oltpbench/blob/master/src/com/oltpbenchmark/benchmarks/wikipedia/WikipediaWorker.java#L168), the maximum length should be [255](https://github.com/oltpbenchmark/oltpbench/blob/master/src/com/oltpbenchmark/benchmarks/wikipedia/data/RevisionHistograms.java#L283), and by default we allow [1024](https://github.com/oltpbenchmark/oltpbench/blob/master/src/com/oltpbenchmark/benchmarks/wikipedia/ddls/wikipedia-mysql-ddl.sql#L149). I skimmed over our TextGenerator code and it looks legit too.

@zhj4655 Are you using the default settings for everything? This is MySQL with our unmodified sample config and ddl? It would help to know what revComment is when it tries to do the illegal execute on [this line](https://github.com/oltpbenchmark/oltpbench/blob/master/src/com/oltpbenchmark/benchmarks/wikipedia/procedures/UpdatePage.java#L208) if you want to try-catch the exception there. Otherwise I can try reproducing it.
