### ISSUE TITLE
I want to load 800 warehouses of tpcc, but it has error

### ISSUE THREAD

**Issue by zhj4655** [oltpbenchmark/oltpbench#266]
I need to load about 80G data to test tpcc, so I set the warehouse to 800, but it does not work.(It can succeed loading data when I set 100 warehouse).
This is the config file:
`<?xml version="1.0"?>
<parameters>
	
    
    <dbtype>mysql</dbtype>
    <driver>com.mysql.jdbc.Driver</driver>
    <DBUrl>jdbc:mysql://localhost:3306/tpcc</DBUrl>
    <username>root</username>
    <password>password</password>
    <isolation>TRANSACTION_REPEATABLE_READ</isolation>
    
    
    <scalefactor>800</scalefactor>
    
    
    <terminals>4</terminals>
    <works>
        <work>
          <warmup>30</warmup>
          <time>600</time>
          <rate>unlimited</rate>
          <weights>45,43,4,4,4</weights>
        </work>
	</works>
	
	  	
   	<transactiontypes>
    	<transactiontype>
    		<name>NewOrder</name>
    	</transactiontype>
    	<transactiontype>
    		<name>Payment</name>
    	</transactiontype>
    	<transactiontype>
    		<name>OrderStatus</name>
    	</transactiontype>
    	<transactiontype>
    		<name>Delivery</name>
    	</transactiontype>
    	<transactiontype>
    		<name>StockLevel</name>
    	</transactiontype>
   	</transactiontypes>	
</parameters>
`

and the error:
`Benchmark:     TPCC {com.oltpbenchmark.benchmarks.tpcc.TPCCBenchmark}
Configuration: config/tpcc_config_mysql.xml
Type:          MYSQL
Driver:        com.mysql.jdbc.Driver
URL:           jdbc:mysql://localhost:3306/tpcc
Isolation:     TRANSACTION_REPEATABLE_READ
Scale Factor:  800.0

22:10:18,367 (DBWorkload.java:263) INFO  - ======================================================================
22:10:18,377 (DBWorkload.java:522) INFO  - Creating new TPCC database...
22:10:18,996 (DBWorkload.java:524) INFO  - Finished!
22:10:18,997 (DBWorkload.java:525) INFO  - ======================================================================
22:10:18,997 (DBWorkload.java:548) INFO  - Loading data into TPCC database...
Exception in thread "main" java.lang.RuntimeException: Unexpected error when trying to load the TPCC database
	at com.oltpbenchmark.api.BenchmarkModule.loadDatabase(BenchmarkModule.java:349)
	at com.oltpbenchmark.api.BenchmarkModule.loadDatabase(BenchmarkModule.java:302)
	at com.oltpbenchmark.DBWorkload.runLoader(DBWorkload.java:813)
	at com.oltpbenchmark.DBWorkload.main(DBWorkload.java:549)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Data source rejected establishment of connection,  message from server: "Too many connections"
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1014)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:988)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:974)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1104)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2412)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2445)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2230)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:813)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.GeneratedConstructorAccessor5.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:399)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:334)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.oltpbenchmark.api.BenchmarkModule.makeConnection(BenchmarkModule.java:120)
	at com.oltpbenchmark.api.Loader$LoaderThread.<init>(Loader.java:58)
	at com.oltpbenchmark.benchmarks.tpcc.TPCCLoader$2.<init>(TPCCLoader.java:94)
	at com.oltpbenchmark.benchmarks.tpcc.TPCCLoader.createLoaderThreads(TPCCLoader.java:94)
	at com.oltpbenchmark.api.BenchmarkModule.loadDatabase(BenchmarkModule.java:324)
	... 3 more
`

What should I do to load  large amounts of data?
Thanks.

**Comment by zhj4655** [comment]
I have solved this problem.
Set mysql's max_connections bigger(I set it to 10000) and it works.
