### ISSUE TITLE
Errow while creating SmallBank database

### ISSUE THREAD

**Issue by arunmarathe** [oltpbenchmark/oltpbench#281]
I get the following error when creating the SmallBank database on a Linux system with MySQL as the backend DBMS.

[root@vm-arunm oltpbench]# ./oltpbenchmark -b smallbank -c ./config/sample_smallbank_config.xml --create=true --load=true --execute=true -s 5 -o outputfile
16:32:08,051 (DBWorkload.java:262) INFO  - ======================================================================

Benchmark:     SMALLBANK {com.oltpbenchmark.benchmarks.smallbank.SmallBankBenchmark}
Configuration: ./config/sample_smallbank_config.xml
Type:          MYSQL
Driver:        com.mysql.jdbc.Driver
URL:           jdbc:mysql://127.0.0.1:4006/smallbank
Isolation:     TRANSACTION_READ_COMMITTED
Scale Factor:  1.0

16:32:08,053 (DBWorkload.java:263) INFO  - ======================================================================
16:32:08,068 (DBWorkload.java:522) INFO  - Creating new SMALLBANK database...
Exception in thread "main" java.lang.RuntimeException: Unexpected error when trying to create the smallbank database
        at com.oltpbenchmark.api.BenchmarkModule.createDatabase(BenchmarkModule.java:258)
        at com.oltpbenchmark.DBWorkload.runCreator(DBWorkload.java:808)
        at com.oltpbenchmark.DBWorkload.main(DBWorkload.java:523)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'smallbank'
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
        at com.mysql.jdbc.Util.getInstance(Util.java:386)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1053)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4096)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4028)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:919)
        at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1694)
        at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1244)
        at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2412)
        at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2445)
        at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2230)
        at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:813)
        at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
        at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:399)
        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:334)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:247)
        at com.oltpbenchmark.api.BenchmarkModule.makeConnection(BenchmarkModule.java:120)
        at com.oltpbenchmark.api.BenchmarkModule.createDatabase(BenchmarkModule.java:254)
        ... 2 more

**Comment by apavlo** [comment]
` Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'smallbank'`

You need to create the database first.
