### ISSUE TITLE
Can't load data for tpch, in MySQL

### ISSUE THREAD

**Issue by zhj4655** [oltpbenchmark/oltpbench#294]
The xml file of tpch:
```
    <!-- Connection details -->
    <dbtype>mysql</dbtype>
    <driver>com.mysql.jdbc.Driver</driver>
    <DBUrl>jdbc:mysql://localhost:3306/tpch</DBUrl>
    <username>root</username>
    <password>1234567890</password>
    <isolation>TRANSACTION_REPEATABLE_READ</isolation>

    <!-- Location for the files generated by tpch dbgen -->
    <datadir>data/tpch1</datadir>

    <!-- Format of the files that contain the tpch data -->
    <!-- Values: csv or tbl-->
    <fileFormat>tbl</fileFormat>

    <!-- This setting doesn't do anything here -->
    <scalefactor>5</scalefactor>
```
When I run the order:
`./oltpbenchmark -b tpch -c config/sample_tpch_config.xml --load=true --create=true`
there are some errors:
```
java.io.FileNotFoundException: data/tpch1/supplier.csv (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileReader.<init>(FileReader.java:72)
	at com.oltpbenchmark.benchmarks.tpch.TPCHLoader$TableLoader.run(TPCHLoader.java:380)
	at java.lang.Thread.run(Thread.java:748)
```
There is a datadir option in the configuration file, but I didn't find the data/tpch1/ files. How can I get them?
Thx

**Comment by apavlo** [comment]
You have to run dbgen:

https://github.com/electrum/tpch-dbgen
https://github.com/gregrahn/tpch-kit

We have been meaning to port over a native Java implementation of it but just haven't had the time.

https://github.com/airlift/tpch
