### ISSUE TITLE
Error running twitter benchmark

### ISSUE THREAD

**Issue by arunmarathe** [oltpbenchmark/oltpbench#308]
I get the following error running the twitter benchmark. I have run it successfully in the past, and the only change in my environment this time around was that recently (few weeks back), I did a git-pull to get the latest oltpbench code.

Thanks,
Arun

`
[arunm@vm-arunm oltpbench]$ ./oltpbenchmark -b twitter -c config/sample_twitter_config.xml --execute=true -s 5 -o outputfile
13:50:17,791 (DBWorkload.java:267) INFO  - ======================================================================

Benchmark:     TWITTER {com.oltpbenchmark.benchmarks.twitter.TwitterBenchmark}
Configuration: config/sample_twitter_config.xml
Type:          MYSQL
Driver:        com.mysql.jdbc.Driver
URL:           jdbc:mysql://127.0.0.1:3306/twitter
Isolation:     TRANSACTION_READ_COMMITTED
Scale Factor:  10.0

13:50:17,793 (DBWorkload.java:268) INFO  - ======================================================================
13:50:17,805 (DBWorkload.java:827) INFO  - Creating 20 virtual terminals...
13:50:17,806 (DBWorkload.java:583) ERROR - Unexpected error when running benchmarks.
java.io.FileNotFoundException: config/traces/twitter_tweetids.txt (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at com.oltpbenchmark.benchmarks.twitter.util.TransactionSelector.<init>(TransactionSelector.java:58)
        at com.oltpbenchmark.benchmarks.twitter.TwitterBenchmark.makeWorkersImpl(TwitterBenchmark.java:56)
        at com.oltpbenchmark.api.BenchmarkModule.makeWorkers(BenchmarkModule.java:235)
        at com.oltpbenchmark.DBWorkload.runWorkload(DBWorkload.java:828)
        at com.oltpbenchmark.DBWorkload.main(DBWorkload.java:581)

`

**Comment by arunmarathe** [comment]
The file that it's complaining about was marked with a D in my code-base. When I restored it, twitter now runs successfully.

I don't remember "git rm"-ing that file, and was it a side-effect of some recent commit?

Thanks.

**Comment by apavlo** [comment]
It is something that you did locally in your repo: https://github.com/oltpbenchmark/oltpbench/tree/master/config/traces
