### ISSUE TITLE
Port SmallBank Benchmark from H-Store

### ISSUE THREAD

**Issue by apavlo** [oltpbenchmark/oltpbench#41]
We have a port of Michael Cahill's _SmallBank_ benchmark available in H-Store. We should port it to our framework so that we can include it in the VLDB paper. It should be pretty straightforward.

Source code is available in the H-Store repository:

https://github.com/apavlo/h-store/tree/master/src/benchmarks/edu/brown/benchmark/smallbank/

**Comment by grooverdan** [comment]
https://travis-ci.org/grooverdan/oltpbench/jobs/214103066

Currently showing a Postgres error. #148 would give more information. Seems like the string is 64 character to match the definition however the exact cause is hidden.
<pre>
04:12:00,875 (SmallBankLoader.java:123) ERROR - Failed to load data
java.sql.BatchUpdateException: Batch entry 0 INSERT INTO "ACCOUNTS" VALUES (0, '0000000000000000000000000000000000000000000000000000000000000000') was aborted.  Call getNextException to see the cause.

	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:134)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:1012)
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1661)
	at com.oltpbenchmark.benchmarks.smallbank.SmallBankLoader$Generator.loadTables(SmallBankLoader.java:129)
	at com.oltpbenchmark.benchmarks.smallbank.SmallBankLoader$Generator.load(SmallBankLoader.java:114)
	at com.oltpbenchmark.api.Loader$LoaderThread.run(Loader.java:65)
	at com.oltpbenchmark.util.ThreadUtil$LatchRunnable.run(ThreadUtil.java:343)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
</pre>

**Comment by eribeiro** [comment]
Sincere question: isn't this issue finished by @apavlo?
