### ISSUE TITLE
LinkBench load references USERTABLE which isn't in schema

### ISSUE THREAD

**Issue by treilly-nuodb** [oltpbenchmark/oltpbench#47]
```
15:02:16,877 (DBWorkload.java:369) INFO  - Loading data into LINKBENCH database...
Exception in thread "main" java.lang.NullPointerException
    at com.oltpbenchmark.util.SQLUtil.getInsertSQL(SQLUtil.java:336)
    at com.oltpbenchmark.util.SQLUtil.getInsertSQL(SQLUtil.java:327)
    at com.oltpbenchmark.util.SQLUtil.getInsertSQL(SQLUtil.java:316)
    at com.oltpbenchmark.benchmarks.linkbench.LinkBenchLoader.load(LinkBenchLoader.java:31)
    at com.oltpbenchmark.api.BenchmarkModule.loadDatabase(BenchmarkModule.java:286)
    at com.oltpbenchmark.api.BenchmarkModule.loadDatabase(BenchmarkModule.java:270)
    at com.oltpbenchmark.DBWorkload.runLoader(DBWorkload.java:481)
    at com.oltpbenchmark.DBWorkload.main(DBWorkload.java:370)
```

**Comment by grooverdan** [comment]
FYI - needs to port https://github.com/mdcallag/linkbench/blob/master/src/main/java/com/facebook/LinkBench/LinkBenchLoad.java#L99
