### ISSUE TITLE
sibench fails to create

### ISSUE THREAD

**Issue by treilly-nuodb** [oltpbenchmark/oltpbench#48]
Seems like its failing to file the ddl file or something.  This is on a linux system, not sure if there's file system case sensitivity issues or something:

```
16:26:04,662 (BenchmarkModule.java:192) ERROR - Failed to find DDL file for SI
Exception in thread "main" java.lang.RuntimeException: Failed to create new instance of SIBenchmark
    at com.oltpbenchmark.util.ClassUtil.newInstance(ClassUtil.java:211)
    at com.oltpbenchmark.util.ClassUtil.newInstance(ClassUtil.java:195)
    at com.oltpbenchmark.DBWorkload.main(DBWorkload.java:284)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at com.oltpbenchmark.util.ClassUtil.newInstance(ClassUtil.java:209)
    ... 2 more
Caused by: java.lang.NullPointerException
    at com.oltpbenchmark.util.FileUtil.readFile(FileUtil.java:184)
    at com.oltpbenchmark.catalog.Catalog.getOriginalTableNames(Catalog.java:293)
    at com.oltpbenchmark.catalog.Catalog.<init>(Catalog.java:98)
    at com.oltpbenchmark.api.BenchmarkModule.<init>(BenchmarkModule.java:94)
    at com.oltpbenchmark.benchmarks.sibench.SIBenchmark.<init>(SIBenchmark.java:22)
    ... 7 more
```

**Comment by grooverdan** [comment]
has been fixed now.
